# -*- coding: utf-8 -*-
"""Basic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xkprsk6DwvDPOENfMamBYtuXF1oSFH8U
"""

print("hello world")